openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
  license:
    name: European Union Public License (EUPL) 1.2
    url: https://interoperable-europe.ec.europa.eu/sites/default/files/custom-page/attachment/eupl_v1.2_en.pdf

paths:
  /example:
    get:
      summary: Example endpoint
      responses:
        '200':
          description: OK
