openapi: 3.0.3
info:
  title: Sample API
  version: 1.0.0

paths:
  /example:
    get:
      summary: Get example resource
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
