openapi: 3.0.3
info:
  title: Sample API
  description: Test API for versioning strategy
  version: "1.2.0"
servers:
  - url: https://api.example.org/v1.2.3
paths:
  /ping:
    get:
      summary: Test endpoint
      responses:
        '200':
          description: OK
